require('dotenv').config();
const { Pool } = require('pg');
const fs = require('fs');
const path = require('path');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

async function generateDDL() {
  const client = await pool.connect();
  try {
    let ddl = '-- Database Schema Dump\n-- Generated by Script\n';
    ddl += '-- Compatibility: Replaced uuid_generate_v4() with gen_random_uuid() for better compatibility (PG 13+ built-in)\n\n';

    // 1. Extensions
    // We prioritize pgcrypto as it provides gen_random_uuid() in older versions and is useful generally
    ddl += '-- Extensions\n';
    ddl += 'CREATE EXTENSION IF NOT EXISTS "pgcrypto";\n';
    // Keep uuid-ossp just in case, but commented out or secondary
    ddl += '-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n\n';

    // 2. Sequences
    const sequencesRes = await client.query(`
      SELECT sequence_name, data_type, start_value, minimum_value, maximum_value, increment, cycle_option
      FROM information_schema.sequences
      WHERE sequence_schema = 'public'
    `);
    if (sequencesRes.rows.length > 0) {
      ddl += '-- Sequences\n';
      for (const seq of sequencesRes.rows) {
        ddl += `DROP SEQUENCE IF EXISTS "${seq.sequence_name}" CASCADE;\n`;
        ddl += `CREATE SEQUENCE "${seq.sequence_name}"`;
        if (seq.data_type) ddl += ` AS ${seq.data_type}`;
        if (seq.increment) ddl += ` INCREMENT BY ${seq.increment}`;
        if (seq.minimum_value) ddl += ` MINVALUE ${seq.minimum_value}`;
        if (seq.maximum_value) ddl += ` MAXVALUE ${seq.maximum_value}`;
        if (seq.start_value) ddl += ` START WITH ${seq.start_value}`;
        if (seq.cycle_option === 'YES') ddl += ` CYCLE`;
        ddl += ';\n';
      }
      ddl += '\n';
    }

    // 3. Tables
    const tablesRes = await client.query(`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
      AND table_type = 'BASE TABLE'
      ORDER BY table_name
    `);

    for (const row of tablesRes.rows) {
      const tableName = row.table_name;
      ddl += `DROP TABLE IF EXISTS "${tableName}" CASCADE;\n`;
      ddl += `CREATE TABLE "${tableName}" (\n`;

      // Columns
      const columnsRes = await client.query(`
        SELECT column_name, data_type, character_maximum_length, is_nullable, column_default
        FROM information_schema.columns
        WHERE table_name = $1 AND table_schema = 'public'
        ORDER BY ordinal_position
      `, [tableName]);

      const colDefs = [];
      for (const col of columnsRes.rows) {
        let colDef = `  "${col.column_name}" ${col.data_type}`;
        
        if (col.character_maximum_length) {
          colDef += `(${col.character_maximum_length})`; // e.g., varchar(255)
        }

        if (col.is_nullable === 'NO') {
          colDef += ' NOT NULL';
        }

        if (col.column_default) {
          let defaultVal = col.column_default;
          // REPLACE uuid_generate_v4() with gen_random_uuid()
          if (defaultVal.includes('uuid_generate_v4()')) {
            defaultVal = defaultVal.replace('uuid_generate_v4()', 'gen_random_uuid()');
          }
          colDef += ` DEFAULT ${defaultVal}`;
        }

        colDefs.push(colDef);
      }

      // Primary Key
      const pkRes = await client.query(`
        SELECT kcu.column_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name
          AND tc.table_schema = kcu.table_schema
        WHERE tc.constraint_type = 'PRIMARY KEY'
        AND tc.table_name = $1
      `, [tableName]);

      if (pkRes.rows.length > 0) {
        const pkCols = pkRes.rows.map(r => `"${r.column_name}"`).join(', ');
        colDefs.push(`  PRIMARY KEY (${pkCols})`);
      }

      ddl += colDefs.join(',\n');
      ddl += '\n);\n\n';
    }

    // 4. Indexes (excluding PK which is handled, and UNIQUE which might be separate constraints but often indexes in PG)
    // Actually, getting indexes is complex. Let's simplify by getting all indexes that are NOT Primary Keys.
    // Note: UNIQUE constraints are often backed by indexes.
    
    const indexesRes = await client.query(`
      SELECT schemaname, tablename, indexname, indexdef
      FROM pg_indexes
      WHERE schemaname = 'public'
    `);

    for (const idx of indexesRes.rows) {
      // Skip PK indexes (usually end with _pkey, but safer to check if it's implicitly created)
      // We'll skip if indexname ends with _pkey for simplicity, or we can rely on "CREATE TABLE" having created the PK index already.
      if (idx.indexname.endsWith('_pkey')) continue;
      
      // Check if it's a UNIQUE constraint index already created by table definition?
      // If we didn't add UNIQUE constraints in CREATE TABLE, we should add them here or as indexes.
      // Our CREATE TABLE above only added PRIMARY KEY. So all other indexes (including UNIQUE) need to be created.
      // However, if the index definition is "CREATE UNIQUE INDEX...", it works fine.
      
      ddl += `${idx.indexdef};\n`;
    }
    ddl += '\n';

    // 5. Foreign Keys
    // We add them at the end to avoid ordering issues
    const fkRes = await client.query(`
      SELECT
        tc.table_name, 
        kcu.column_name, 
        ccu.table_name AS foreign_table_name,
        ccu.column_name AS foreign_column_name,
        tc.constraint_name
      FROM 
        information_schema.table_constraints AS tc 
        JOIN information_schema.key_column_usage AS kcu
          ON tc.constraint_name = kcu.constraint_name
          AND tc.table_schema = kcu.table_schema
        JOIN information_schema.constraint_column_usage AS ccu
          ON ccu.constraint_name = tc.constraint_name
          AND ccu.table_schema = tc.table_schema
      WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = 'public'
    `);

    if (fkRes.rows.length > 0) {
      ddl += '-- Foreign Keys\n\n';
      for (const fk of fkRes.rows) {
        ddl += `ALTER TABLE "${fk.table_name}" ADD CONSTRAINT "${fk.constraint_name}" FOREIGN KEY ("${fk.column_name}") REFERENCES "${fk.foreign_table_name}" ("${fk.foreign_column_name}");\n`;
      }
    }

    fs.writeFileSync(path.join(__dirname, 'schema_dump.sql'), ddl);
    console.log('DDL generated successfully at schema_dump.sql');

  } catch (err) {
    console.error('Error generating DDL:', err);
  } finally {
    client.release();
    await pool.end();
  }
}

generateDDL();
